import json
import requests
from argparse import ArgumentParser
from datetime import datetime
import os, glob

arg_parser = ArgumentParser()
arg_parser.add_argument("api_key", help="Currencylayer API Key")
arg_parser.add_argument("input_file", help="JSON file generated by chat-replay-downloader")
arg_parser.add_argument("output_file", help="Output file")
arg_parser.add_argument("-c", help="Currency convertion file", dest="currency_convertion_file", default="currency_convert.json")
arg_parser.add_argument("-t", help="Target Currency. Default TWD.", dest="target_currency", default="TWD")
args = arg_parser.parse_args()

FILE_NAME = args.input_file
OUTPUT_NAME = args.output_file
API_KEY = args.api_key
CURRENCY_CONVERT_FILE = args.currency_convertion_file
EXCHANGE_FILE_PREFIX = "exchange"
TARGET_CURRENCY = args.target_currency

def get_currency_and_amount(s):
    head = s.rstrip('0123456789.,')
    tail = s[len(head):]
    return head.strip(), tail.replace(",", "").strip()

# 獲取匯率，一天更新一次

global __convertion_rates
date = datetime.today().strftime('%Y%m%d')
__convertion_rates_file_name = f"{EXCHANGE_FILE_PREFIX}.{date}.json"

if os.path.isfile(__convertion_rates_file_name):
    with open(__convertion_rates_file_name) as f:
        __convertion_rates = json.load(f)
else:
    for filename in glob.glob(f"./{EXCHANGE_FILE_PREFIX}*"):
        os.remove(filename) 
    __convertion_rates = requests.get(f'http://api.currencylayer.com/live?access_key={API_KEY}').json()["quotes"]
    with open(__convertion_rates_file_name, 'w') as json_file:
        json.dump(__convertion_rates, json_file)

def convert_currency(currency, amount):
    global __convertion_rates
    return amount / __convertion_rates["USD" + currency] * __convertion_rates[f"USD{TARGET_CURRENCY}"]

result = {}

with open(FILE_NAME) as f:
  datas = json.load(f)
  
  for data in datas:
    currency, amount = get_currency_and_amount(data['amount'])
    result[currency] = result.get(currency, 0.0) + float(amount)

with open(OUTPUT_NAME, 'w', encoding='utf8') as json_file:
  json.dump(result, json_file, ensure_ascii=False)

# 開始貨幣轉換

sum = 0.0

with open(CURRENCY_CONVERT_FILE, encoding='utf8') as f:
    convert_table = json.load(f)

    for currency in result:
        converted_currency = ""
        if currency in convert_table:
            converted_currency = convert_table[currency]
        else:
            converted_currency = currency.replace("$", "D")

        tmp = convert_currency(converted_currency, result[currency])
        sum += tmp
    print(f"Sum: {sum} {TARGET_CURRENCY}")